Importing **Numpy**

In [2]:
import numpy as np

Create **Numpy** arrays which is more feasible and has more advantages over classical arrays.

In [3]:
print('1d array')
a = np.array([1,2,3,4,5,5,6])
print(a)

print('2d array')
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

print('3d array')
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15.99]]])
print(c)
print()
print(type(a))
print(a.size) #tells us number of elements in array
print(b.size)
print(c.size)
print(a.dtype)
print(c.dtype)

1d array
[1 2 3 4 5 5 6]
2d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3d array
[[[ 1.    2.    3.    4.    5.  ]
  [ 6.    7.    8.    9.   10.  ]
  [11.   12.   13.   14.   15.99]]]

<class 'numpy.ndarray'>
7
10
15
int32
float64


You can also use `matrix_name.T` for transpose of the matrix.

In [4]:
#transpose replace rows with columns and columns with rows:
d = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15.99]])
print(d.transpose())

[[ 1.    6.   11.  ]
 [ 2.    7.   12.  ]
 [ 3.    8.   13.  ]
 [ 4.    9.   14.  ]
 [ 5.   10.   15.99]]


`np.linalg` is a module in NumPy (Numerical Python) that
provides functions for linear algebra operations.

when there's no solutions or infinite solutions then least squares used to find best fit lines.

In [5]:
#This function specifically solves a linear least squares problem. This means it
#finds the "best fit" solution when the system of equations Ax = b has no exact solution
#(i.e., the system is overdetermined or inconsistent).
def solve_linear_least_squares(A, b):

  x = np.linalg.lstsq(A, b, rcond=None)[0]
  return x

# Example usage:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array( [1, 2, 4] )

x = solve_linear_least_squares(A, b)
print(x) # To see the output, run the code.


[0.25       0.16666667 0.08333333]


In [6]:
# Create the NumPy array A
A = np.array([
    [1, 2, 3],
    [1, 1, 2],
    [0, 0, 1]
])

# Create the NumPy array b
b = np.array([1, 5, 9])

# Solve the linear equation system Ax = b
print(f"determinant of the matrix is: {np.linalg.det(A)}.")
print(f"rank of the matrix is: {np.linalg.matrix_rank(A)}.")
try:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
except np.linalg.LinAlgError:
    print("Matrix A is singular (not invertible).")


#
x = np.linalg.solve(A, b)

# Display the result
print(x)

determinant of the matrix is: -1.0.
rank of the matrix is: 3.
Inverse of A:
 [[-1.  2. -1.]
 [ 1. -1. -1.]
 [ 0.  0.  1.]]
[  0. -13.   9.]


In [7]:
# Define the matrices
A = np.array([
    [1, 2, 3],
    [1, 1, 2],
    [0, 0, 1]
])
b = np.array([1, 5, 9])

# Calculate and print matrix properties
det_A = np.linalg.det(A)
rank_A = np.linalg.matrix_rank(A)
print(f"Determinant of A: {det_A:.2f}")  # Format determinant with 2 decimal places
print(f"Rank of A: {rank_A}")

# Check for invertibility and calculate inverse
if np.linalg.det(A) != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix A is singular (not invertible).")

# Solve the linear equation system
x = np.linalg.solve(A, b)
# x = np.linalg.lstsq(A, b, rcond=None)[0]  # Use lstsq instead of solve, if solution not possible

# Print the solution
print("Solution (x):\n", x)

Determinant of A: -1.00
Rank of A: 3
Inverse of A:
 [[-1.  2. -1.]
 [ 1. -1. -1.]
 [ 0.  0.  1.]]
Solution (x):
 [  0. -13.   9.]


In [8]:
import numpy as np
C = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

D = np.array([1,2,4])
det = np.linalg.det(C)
if(det == 0):
  print("Matrix is singular, so try another or below's least square best fit!")
else:
  print(np.linalg.solve(C,D))
print(np.linalg.lstsq(C,D,rcond=None)[0])


[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
[0.25       0.16666667 0.08333333]


In [9]:
#projection of b onto a is there, compute it from p = x^ . A
b = np.array([[1],
              [1]])
a = np.array([[1],
              [-1]])
trans_b=b.T
trans_a=a.T

x = np.dot(a.T, b) / np.dot(a.T, a)
projcetion_p = np.dot(x,a.T)
print(x)
print(projcetion_p)


[[0.]]
[[0. 0.]]
